sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mondo192/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true mondo192/react-test npm run test -- --coverage

after_success:
  - docker build -t mondo192/multi-client ./client
  - docker build -t mondo192/multi-nginx ./nginx
  - docker build -t mondo192/multi-server ./server
  - docker build -t mondo192/multi-worker ./worker 



deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-eu-west-1-125892290802
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY